### ISSUE TITLE
Ideas for Super Nerd

### ISSUE THREAD

**Issue by nihal127** [blahsd/supernerd.widget#2]
I'm using Betterbar right now, and would like to see battery here too, I would do it myself but I think that it was also be better here. I would attach my .coffee but I don't know how too.

**Comment by blahsd** [comment]
That's definitely on the to do list! Glad to hear that it would be appreciated :) Just for the sake of keeping track of everything, I'd ask you to open a specific issue with a descriptive title - its not an issue if we end up having many issues (hehee) open, but it is if everybody types up something in here because good ideas might get lost! So one idea = one issue.

**Comment by blahsd** [comment]
Implemented in last commit.
