### ISSUE TITLE
Almost everything showing up in plain text and I still can't click the menu bar

### ISSUE THREAD

**Issue by CobreDev** [blahsd/supernerd.widget#21]
Almost everything is showing up in plain text besides the menu bar (which I still can't click on). Also, how can I reposition them?

**Comment by blahsd** [comment]
- What do you mean by plain text exactly?
- The click thing we went over – it doesn't have to do with the widget, it's an issue of Ubersicht settings
- Positioning is done in the .CSS files. You can edit anything related to appearance in there. Find it in supernerd.widget/styles/mono.css .

**Comment by CobreDev** [comment]
I mean it shows up all overlapped and in plain text (just words on the screen, not outlined or in any sort of box thing). The menu bar is nice, I can see that, but everything else is not good. 

I tried what you said for the click thing, I can do it with a modifier key, (super buggy) but if I run the command, I can’t click it. 

What is the name of the .css file?

Thanks,
Cooper

**Comment by blahsd** [comment]
Hey Cooper,

it's a bit hard for me to diagnose this because everything works properly for me, so I'm not sure what the culprit could be. The only thing that comes to my mind is that your folder structure might be messed up. Make sure your Ubersicht folder is set up like this:

```
- Ubersicht/
-- widgets/
--- supernerd.widget/
---- styles/
----- mono.css
----- mini.css
----- [etc.]

---- scripts/
----- [etc.]

---- bar-top.coffee
---- bar-bottom.coffee
---- [etc.]
```

With regards to the clicking thing, I really have no clue. If you deactivate your desktop I really have no idea why you wouldn't be able to click through – this is an issue with Ubersicht though, not with the widget itself, so you should probably bring it up on they're repo. 

Sorry that I can't be of any more help!

**Comment by blahsd** [comment]
I'm assuming this was fixed. Feel free to reopen if necessary
