### ISSUE TITLE
Add other music players integration (Swinsian, ncmpcpp, ...)

### ISSUE THREAD

**Issue by blahsd** [blahsd/supernerd.widget#7]

**Comment by conxr** [comment]
+1, swinsian and/or ncmpcpp would be cool too

**Comment by blahsd** [comment]
Spotify done on master branch.

@conxr I have no idea how to do swinsian, are you able to help?

**Comment by conxr** [comment]
@blahsd Yeah I gave it a bash, copied the itunes section in the applescript, since swinsian is almost identical, but no luck as of yet. Will update you if I can manage to fix it! 

Is there also a way of having both options, sometimes I'll listen to spotify, then others swinsian, would be nice if they both worked simultaneously.

**Comment by blahsd** [comment]
@conxr options are now removed, it works concurrently with iTunes and Spotify. It currently gives preference to iTunes, it's possible to switch it easily just by moving one block of code over the other. Let me know how it goes with swinsian.

**Comment by conxr** [comment]
Thanks for the update! However, Spotify isn't showing for me with the new method, but itunes seems to be fine.
<img width="1440" alt="screen shot 2018-03-03 at 20 28 24" src="https://user-images.githubusercontent.com/31190088/36938985-c8e0220a-1f21-11e8-9f90-264c2413b020.png">
I think Swinsian perhaps requires it's own API key, gonna dig further through the week.

**Comment by blahsd** [comment]
@conxr mpd is now integrated!
